# Serilog 日志记录相关配置

[Serilog]
    # Serilog 引用的程序集
    Using = ["Serilog.Sinks.Console", "Serilog.Sinks.File"]
    # 日志记录的扩展信息
    Enrich = ["FromLogContext"]
    # 最低日志等级 
    MinimumLevel = "Information"

# 控制台记录器
[[Serilog.WriteTo]]
    Name = "Console"

# 文件记录器
[[Serilog.WriteTo]]
    Name = "File"
[Serilog.WriteTo.Args]
    # 日志文件路径
    Path = "logs/yuki/.log"
    # 日志滚动周期
    RollingInterval = "Day"
    # 与其他进程共享日志文件
    Shared = true
